### ISSUE TITLE
How to delete torctl on ubuntu server

### ISSUE THREAD

**Issue by 1YablochnIK1** [BlackArch/torctl#11]
I'm using last version ubuntu server.

**Comment by sepehrdaddev** [comment]
This tool is a regular shell script so if you delete the script, it will be removed.

**Comment by martin-braun** [comment]
@sepehrdaddev I think he is referring to autostart. How to undo that?

**Comment by Edu4rdSHL** [comment]
`systemctl disable --now torctl-autostart.service torctl-autowipe.service` should work.
