### ISSUE TITLE
Network stop working in ArchLinux

### ISSUE THREAD

**Issue by martin-braun** [BlackArch/torctl#12]
[I installed `torctl`](https://bennybackslash.github.io/%2Fposts%2FTorctl%20on%20Arch.html) on ArchLinux a while back and it worked great for quite some time. Recently, I had to disable the service for larger services and when I turned it back on my internet stopped working. My internet works fine when the service is disabled, though.

I tried to reinstall torctl and the result remain the same: 

<img width="728" alt="Screen Shot 2021-03-20 at 23 12 31" src="https://user-images.githubusercontent.com/24259245/111886936-f6664600-89d1-11eb-9d42-e9e3a5634429.png">

I'm quite new to ArchLinux, I wonder how I can troubleshoot this issue, now. Any help is appreciated.

**Comment by Edu4rdSHL** [comment]
Hello, you have internet because you can ping ip addresses, what do you have are DNS issues. Can you please check what do you have in `/etc/resolv.conf` when the problem appears?

**Comment by martin-braun** [comment]
@Edu4rdSHL Thanks for your reply. Only DNS issues? Shouldn't the direct ping to an external IP work, though?

Here are the contents of `/etc/resolv.conf`:
<img width="496" alt="Screen Shot 2021-03-21 at 02 34 21" src="https://user-images.githubusercontent.com/24259245/111890898-2de2eb80-89ee-11eb-8f4c-dfa7727e7de2.png">

Best regards!

**Comment by Edu4rdSHL** [comment]
Hi, you're right. Can you please list the steps to reproduce the issue? If I understand correctly I need to:

- start torctl
- stop torctll
- start again

At this point the network doesn't work. Is that correct?

**Comment by martin-braun** [comment]
@Edu4rdSHL I think it will be hard to reproduce the issue, that's why I ask how I can troubleshoot this issue now. Here is what happened: 

I installed Arch Linux on a VirtualBox VM over a month, ago. My first linux ever, everything worked fine including my network. Then I followed [this tutorial](https://bennybackslash.github.io/%2Fposts%2FTorctl%20on%20Arch.html) to get `torctl` installed. I enabled it, including autostart, things worked, I checked my IP using `curl icanhazip.com` and it was different. Quite happily I got myself into installing yay to get access to AUR repos using [this tutorial](https://www.tecmint.com/install-yay-aur-helper-in-arch-linux-and-manjaro/). Works, too. Updated all packages and everything went fine.

Then, I wanted to install `bitcoin-core` [from AUR](https://aur.archlinux.org/packages/bitcoin-core/). I don't think this is related, but my installation failed, because it reports `fatal error: in "arith_uint256_tests/basics": std::runtime_error: locale::facet::_S_create_c_locale name not valid` and `Assertion 'ret.second' failed`. After that my internet still worked through TOR, it even worked after restarting. I had to move on, because of several other projects so my VM was shut down for almost a 3 weeks. 

Recently I started the VM again, torctl started with it, too. I tried to install `bitcoin-core` again, I really forgot the issue and wanted to refresh my memory to finally find a solution for this problem. I got the same error, so I decided to try the whole thing without running torctl, so I run `sudo torctl stop`. This was the moment of doom. Internet still works, but as soon as I turn `torctl` I get the internet problems that I report here, now.

It does not matter if I restart or not, it does not matter if torctl was shutdown or started after boot. Whenever `torctl` is on, my internet does not work anymore. Now you know everything I know.

I don't expect a perfect solution, but I would appreciate any tips to find the root cause of the problem. So, how can I troubleshoot this, what can I try to find the reason for this error?

Thank you so much in advance! I'm happy for any help.

**Comment by Edu4rdSHL** [comment]
Hello, thank you for the detailed explanation. What I can conlude from what you have said is that `torctl` was working fine until you stopped it. I will try today in a VM and see if I can reproduce the issue. My guess is that at some point the files in the backup dir got wiped and then torctl was not able to restore the backup files. https://github.com/BlackArch/torctl/blob/c718d9e04ab21922fba80ae105aa3df9d1c58616/torctl#L63-L64

My guess is that the `iptables` rules were messed up and therefore it doesn't work.

I'm not the developer of this script but I'm sure that putting a backup dir in `/tmp` was the worse idea. I will back to you soon.

**Comment by kinggx9** [comment]
I have a similar situation

**Comment by martin-braun** [comment]
@Edu4rdSHL Thank you for investigating. This really looks like the cause of the issue, but I cannot confirm this, because in the attempt to get a fix I reverted my machine to a state when it was working. My internet works again, but as soon as I enable `torctl` it losses all packages, but when I turn it off, my internet works again.

Something is really broken, I tried to update everything and rebooted, but the issue remains. I have to investigate further, later.

**Comment by pwnfoo** [comment]
Adding in my 2 cents here.

I tried toggling torctl multiple times to see if anything would break. Unfortunately everything seems fine for me :(

> My guess is that at some point the files in the backup dir got wiped and then torctl was not able to restore the backup files.

This makes sense; There's a lot of `.bak` files that are backed up there, and it's quite possible something was nuked from `/tmp`


> Something is really broken, I tried to update everything and rebooted, but the issue remains. I have to investigate further, later.

@martin-braun Can you report back with the following?

* Is this an isolated incident to an Arch box only?
* Is Tor working fine? Without starting torctl in your fresh box, please make sure what you can browse internet through tor
    * Once that's done, start torctl when tor service is ALREADY running. See if you still have issues when that happens? If you lose internet after this, we can be reasonably sure it's messing up some config.


![image](https://user-images.githubusercontent.com/9546091/112743075-b85cb980-8fb1-11eb-8039-76899fa1295e.png)

**Comment by kinggx9** [comment]
The reason is not at BACKUPDIR="/tmp/torctl" 
I got an error due to the xorg and xfce4 xfce4-goodies upgrade
Everything should be working properly before the upgrade

**Comment by kinggx9** [comment]
The error occurred due to an update of xxxx
The temporary fix is to revert to an earlier version:
pacman -U https://archive.archlinux.org/packages/t/tor/tor-0.4.4.6-1-x86_64.pkg.tar.zst
I hope there is a better solution

**Comment by Edu4rdSHL** [comment]
Hi, it should be fixed in the 0.5.7 release of `torctl`, I've updated the script and the package in our repos, let's wait for the update. If you want to go ahead, you can replace the `/usr/bin/torctl` script for the one in https://raw.githubusercontent.com/BlackArch/torctl/master/torctl and this should work.

Please let me know if you have any other problems.

**Comment by martin-braun** [comment]
_/previous comment removed_

EDIT: 

Thank you for taking care of this issue. @Edu4rdSHL @kinggx9 @pwnfoo really appreciate your help! =)

Just for the record. My ip tables were broken after the update. I had to run `iptables-restore /etc/iptables/iptables.rules` and now everything works again.

So happy! =)

**Comment by Edu4rdSHL** [comment]
@martin-braun looks like a problem with your system, which distro is and which kernel version are you using?

It's working fine here

![image](https://user-images.githubusercontent.com/32582878/113055882-b725bb00-9170-11eb-8775-bdbecd8084af.png)

**Comment by martin-braun** [comment]
@Edu4rdSHL Wow you gave such a quick response, I just edited my previous comment, because I found a solution, already. Thank you again. ❤️

**Comment by sergii-trix** [comment]
Hello! I have a similar problem. Sorry, but I use a translator. Therefore, something may be incomprehensible. I lose the Internet when I turn it on. 

https://user-images.githubusercontent.com/88038299/127427094-30eac39c-1580-429c-8df4-e11195edc431.mp4

**Comment by martin-braun** [comment]
@sergii-trix what does `sudo systemctl status tor.service` output? Also update all packages and try to run `iptables-restore /etc/iptables/iptables.rules` and `sudo reboot`.

**Comment by sergii-trix** [comment]
@martin-braun 

https://user-images.githubusercontent.com/88038299/127673244-1519a2e9-1c08-4dda-bab1-65c0350674cc.mp4


https://user-images.githubusercontent.com/88038299/127673326-abe53716-4bb1-4485-825b-3bfd044eec9a.mp4

**Comment by sergii-trix** [comment]
@martin-braun 

https://user-images.githubusercontent.com/88038299/127673755-f97a0174-91eb-4bba-86b5-a263e7e06fe5.mp4


https://user-images.githubusercontent.com/88038299/127673778-367857e4-4206-4451-b7ac-5c1d515b18ed.mp4

**Comment by sergii-trix** [comment]
I did it myself. Used bridges. Tor couldn't just connect.

**Comment by avgust-in** [comment]
if you must connect via "UseBridges", for example in /etc/tor/torrc
network is down when torctl starts
*torctl rewrite /etc/tor/torrc, and other files (you can find in `cat /usr/local/bin/torctl | grep '.bak'`)
my fix is use: `chattr +i /etc/tor/torrc`
I am currently testing my anonymity.
