### ISSUE TITLE
autostart service stopped working

### ISSUE THREAD

**Issue by martin-braun** [BlackArch/torctl#13]
Since version 0.5.7 my autostart service is not working. I enabled it like so:

<img width="458" alt="Screen Shot 2021-04-12 at 23 40 22" src="https://user-images.githubusercontent.com/24259245/114466525-e44e8080-9be8-11eb-9727-cd2852110755.png">

But when I reboot I get this: 

<img width="629" alt="Screen Shot 2021-04-12 at 23 40 46" src="https://user-images.githubusercontent.com/24259245/114466552-ec0e2500-9be8-11eb-8afb-0fbf1c3094c7.png">

Only after running `sudo torctl restart` it will be fixed until my next reboot, again. 

I also tried to disable all services with `sudo systemctl disable --now torctl-autostart.service torctl-autowipe.service`, rebooted, activated the services again and rebooted another time, but the issue remains.

**Comment by Edu4rdSHL** [comment]
Enable `tor.service` to run at boot.

**Comment by martin-braun** [comment]
> Enable `tor.service` to run at boot.

Like so?

<img width="1004" alt="Screen Shot 2021-06-05 at 20 32 13" src="https://user-images.githubusercontent.com/24259245/120901832-5b2e5580-c63d-11eb-8773-3a281decea30.png">

The issue remains ...

**Comment by Edu4rdSHL** [comment]
I just tested and it's working as expected. Make sure to use the latest version of torctl.

![image](https://user-images.githubusercontent.com/32582878/120909160-b4a87b80-c661-11eb-936d-0d835a982eda.png)

Also you aren't giving any relevant detail like the OS that you're using, the version and the output of `systemctl status torctl-autostart.service`, if you give these details I can help you more.

**Comment by martin-braun** [comment]
Thank you, my TOR wasn't up2date and for some reason yay was broke. I sorted things out, now it's working, again.

**Comment by martin-braun** [comment]
@Edu4rdSHL autostart service stopped working again. Here is how to reproduce:

- Update all packages
- Disable everything TOR related and reboot like so:
```bash
sudo torctl stop
sudo systemctl disable --now tor.service torctl-autostart.service torctl-autowipe.service
sudo reboot
```
- Enable everything again like so: 
```bash
sudo systemctl enable tor.service
sudo torctl autostart
sudo torctl autowipe
sudo torctl start
```
- Now execute these commands to check everything looks good:
```bash
sudo systemctl status tor.service torctl-autostart.service torctl-autowipe.service
sudo torctl status
```
Output:
<img width="991" alt="Screen Shot 2021-06-20 at 19 30 37" src="https://user-images.githubusercontent.com/24259245/122683206-07576b00-d1fe-11eb-8344-370e063b0a89.png">
Also `curl -4 icanhazip.com` returns foreign IP. So far so good.
- Now `sudo reboot` and execute `sudo systemctl status tor.service torctl-autostart.service torctl-autowipe.service`
Output:
<img width="999" alt="Screen Shot 2021-06-20 at 19 33 03" src="https://user-images.githubusercontent.com/24259245/122683261-5bfae600-d1fe-11eb-8944-5b99f10c30fd.png">
