### ISSUE TITLE
route docker traffic possible?

### ISSUE THREAD

**Issue by diiirt** [BlackArch/torctl#15]
is it possible to get this to work with docker containers?  I have tried running the container with the '--network host' flag but it still doesn't route the traffic through tor.  Thanks!

**Comment by noraj** [comment]
[Configure Docker to use a proxy server](https://docs.docker.com/network/proxy/) using the [socks port](https://github.com/BlackArch/torctl/blob/master/torctl#L27)

**Comment by noraj** [comment]
It may be a problem if docker client supports only HTTP(S) and FTP proxy but not SOCKS ones

**Comment by diiirt** [comment]
Thanks for the response but I couldn't get it to work.  I tried setting up the proxy as in the link to 127.0.0.1:9050 but the container doesn't seem to care. I was trying use torctl with https://github.com/vector-im/element-web, maybe their docker version doesn't support socks.

**Comment by noraj** [comment]
The docker client seems to not support SOCKS proxy for now

**Comment by noraj** [comment]
> Thanks for the response but I couldn't get it to work. I tried setting up the proxy as in the link to 127.0.0.1:9050 but the container doesn't seem to care. I was trying use torctl with https://github.com/vector-im/element-web, maybe their docker version doesn't support socks.

The address should be `socks5h://localhost:9050` see [AL wiki](https://wiki.archlinux.org/title/Tor#Usage) and not `127.0.0.1:9050`. But since docker doesn't support it you can setup a HTTP proxy reading the [AL wiki](https://wiki.archlinux.org/title/Tor#HTTP_proxy).
