### ISSUE TITLE
[Feature Request] add VanillaOS support

### ISSUE THREAD

**Issue by mateowoetam** [BlackArch/torctl#27]
[VanillaOS](https://vanillaos.org/) is an Ubuntu-based distribution that uses immutability through [ABroot](https://github.com/Vanilla-OS/ABRoot) and [apx](https://github.com/vanilla-os/apx); it would be nice if there were a straightforward way to install torctl in this type of environment.

**Comment by noraj** [comment]
If you review https://github.com/BlackArch/torctl/blob/master/torctl you can see there are a bunch of iptables, sysctl, maccachanger, etc. nothing specific to ArchLinux. What's not working on Ubuntu? I guess all works on Unbuntu and what you are asking is a package for Ubuntu? But you realize that we are BlackArch Linux right? You can't ask a distro to provide package for other distro? All I can tell you is: [here](https://github.com/BlackArch/blackarch/blob/master/packages/torctl/PKGBUILD) is the PKGBUILD for BA and [here](https://documentation.vanillaos.org/docs/packaging/) is the packaging documentation for VanillaOS. Happy packaging!
