### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by sTiKyt** [BlackArch/torctl#7]
![image](https://user-images.githubusercontent.com/35602029/95690311-4d3b4880-0c06-11eb-96b2-2c54907cd16c.png)
![image](https://user-images.githubusercontent.com/35602029/95690321-5debbe80-0c06-11eb-9ddf-6274aed5c5bf.png)
![image](https://user-images.githubusercontent.com/35602029/95690327-6ba14400-0c06-11eb-95e0-5941fd122e7b.png)

**Comment by sepehrdaddev** [comment]
@sTiKyt, It's fixed in version v0.5.6

Thanks for letting me know

**Comment by sTiKyt** [comment]
It was fixed is 5.0.6, i can confirm, thanks for your owrk.

**Comment by itsmaybetokyo** [comment]
I'm on 0.5.7 and I'm having this same issue
