### ISSUE TITLE
GUI for this wonder script.

### ISSUE THREAD

**Issue by bm16ton** [BlackArch/torctl#9]
Hello, let me first say thank you! This script is amazing! It took only slight modification to make work on Ubuntu. the uid is different on diff distros, tor-router has a nice a check in their script. Anyway In an attempt to get better at scripting I wrote a simple gui using gtkdialog for your script;
https://github.com/bm16ton/tor-gui
It works well. Im gonna add support for saving current mac addr for recovery because sum nics like my ath10k_snoc doesn't have a hardware addr, so it cant recover it. I use the same fake one to keep from getting a new IP every boot. Also I noticed I cant pass X11 forwarding thru ssh after tor disconnect (sometimes if I wait for a long time itll recover) So I added restarting ssh/networking on shutdown, that seems to allow X11 forwarding immediately after. And what else oh ipv6 would take a while to recover after shutdown, tried restarting services but that didnt help, but using nmcli to reapply settings brings it back. As I said im terrible at writing scripts etc, im sure i did things the forrest gump method and if you ever check it out and see anything done stupidly pls let me know!.
Again your amazing! Thank you! And I made sure to give you the credit in the README and when it shows the start/stop results it displays the  --==[ torctl.sh by blackarch.org ]==--  If I can give you credit in a better or different way please let me know.

**Comment by Edu4rdSHL** [comment]
Please create a pull request for these kind of changes.
